In [1]:
import pandas as pd
df=pd.read_excel("Credit_cards_App_data.xlsx")

In [2]:
df.head()

,Application id,first_name,last_name,email,gender,address,age,tdecision,empstaus,ExCus (Customer in Past),Source,Salary,ExDebt (Liability),Booking,INT_ID,Prev_ID,AGT_ID,Booking_Amt
0,1,Dollie,Scafe,dscafe0@is.gd,Female,02 Garrison Pass,34,Pending,SE,Y,EC,127110,25130,NaN,6869736235,79-489-1539,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6...,NaN
1,2,Austin,Pennycook,apennycook1@mac.com,Male,007 Miller Road,57,Approve,SE,Y,D,464039,22311,Y,9694176212,92-247-0058,Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-TW...,278423.4
2,3,Mareah,Tomanek,mtomanek2@bloomberg.com,Female,145 Charing Cross Junction,57,Approve,SE,Y,3P,584420,28557,Y,152387684,36-236-3028,Mozilla/5.0 (Windows NT 5.1; rv:21.0) Gecko/20...,350652.0
3,4,Myrna,Rosenthaler,mrosenthaler3@dmoz.org,Female,268 Algoma Hill,59,Approve,SE,Y,3P,583781,26042,Y,6510396556,34-339-0917,Mozilla/5.0 (Windows; U; Windows NT 6.1; cs-CZ...,350268.6
4,5,Danyette,Stempe,dstempe4@tumblr.com,Female,571 Stone Corner Park,51,Approve,SE,N,MP,551718,27892,Y,7141853006,94-098-8902,Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_2_1 li...,331030.8

In [4]:
df[['Application id','email']].duplicated().sum()

0

In [19]:
df[df.tdecision =='Decline'][df.Booking=='Y']

C:\Users\HIMANSHU\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

Empty DataFrame
Columns: [Application id, first_name, last_name, email, gender, address, age, tdecision, empstaus, ExCus (Customer in Past), Source, Salary, ExDebt (Liability), Booking, INT_ID, Prev_ID, AGT_ID, Booking_Amt]
Index: []

In [20]:
df.loc[df.Salary<df['ExDebt (Liability)'],:]

,Application id,first_name,last_name,email,gender,address,age,tdecision,empstaus,ExCus (Customer in Past),Source,Salary,ExDebt (Liability),Booking,INT_ID,Prev_ID,AGT_ID,Booking_Amt
9,10,Kim,Arne,karne9@infoseek.co.jp,Male,6568 Dwight Point,45,Decline,NSE,N,MP,25439,26082,NaN,3383749711,75-757-9174,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_2)...,NaN
19,20,Gracie,Winear,gwinearj@devhub.com,Female,9800 Ridge Oak Crossing,38,Decline,SE,Y,D,9021,21121,NaN,1670564037,20-195-4948,Mozilla/5.0 (Windows NT 6.0) AppleWebKit/534.2...,NaN
92,93,Wallis,Doge,wdoge2k@sun.com,Female,1 Leroy Place,42,Decline,SE,Y,D,5291,24362,NaN,1073943895,05-981-8413,Mozilla/5.0 Slackware/13.37 (X11; U; Linux x86...,NaN
144,145,Vinita,Gallandre,vgallandre40@time.com,Female,16 Banding Point,57,Decline,SE,Y,D,11319,25111,NaN,2509361465,27-081-8731,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_4_1...,NaN
149,150,Basilius,Bamlet,bbamlet45@google.cn,Male,7789 Logan Parkway,32,Pending,NSE,N,EC,6390,23691,NaN,1250011809,19-759-1267,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_0)...,NaN
163,164,Torry,Raddan,traddan4j@edublogs.org,Male,0 Graedel Center,34,Decline,SE,Y,D,24053,26254,NaN,2292321963,70-485-8567,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5)...,NaN
219,220,Kerr,Paydon,kpaydon63@gizmodo.com,Male,10635 Mayfield Avenue,25,Decline,NSE,N,D,1473,23763,NaN,1626078947,33-002-3661,Mozilla/5.0 (X11; Linux amd64) AppleWebKit/535...,NaN
245,246,Mavra,Henker,mhenker6t@amazon.de,Female,30286 Glendale Alley,58,Pending,SE,Y,EC,18913,27781,NaN,907846548,31-121-0688,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6...,NaN
276,277,Raynard,Hammel,rhammel7o@w3.org,Male,94 Sullivan Hill,44,Decline,SE,N,3P,16930,24558,NaN,2915194440,42-833-1261,Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKi...,NaN
279,280,Margareta,Aleksankov,maleksankov7r@tinypic.com,Female,69 East Road,43,Decline,SE,Y,D,15436,22318,NaN,182486974,03-636-4745,Mozilla/5.0 (Windows NT 6.1; rv:14.0) Gecko/20...,NaN
295,296,Barde,Rounds,brounds87@example.com,Male,7652 Graceland Court,53,Pending,NSE,Y,EC,4224,23067,NaN,2290564435,15-764-9454,Mozilla/5.0 (compatible; Googlebot/2.1; +http:...,NaN
311,312,Hedwiga,Habens,hhabens8n@tumblr.com,Female,47 International Alley,57,Pending,SE,Y,EC,13278,26911,NaN,8527489074,90-554-3472,Mozilla/5.0 (X11; Linux i686) AppleWebKit/535....,NaN
319,320,Julianne,Francesco,jfrancesco8v@stanford.edu,Female,4520 Crownhardt Hill,51,Pending,NSE,Y,EC,4883,23070,NaN,763750239,94-356-9902,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6...,NaN
338,339,Pascal,Habbes,phabbes9e@themeforest.net,Male,724 Division Hill,53,Pending,SE,N,EC,11900,29987,NaN,7224599573,24-162-6471,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5...,NaN
354,355,Melamie,Chiplen,mchiplen9u@w3.org,Female,58189 Mallory Lane,36,Decline,NSE,Y,MP,8004,26047,NaN,2325330117,80-207-8074,Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:22...,NaN
417,418,Lanette,Mc Gorley,lmcgorleybl@constantcontact.com,Female,408 Springview Point,30,Pending,SE,N,EC,2110,27129,NaN,4447180898,35-059-5707,Mozilla/5.0 (Windows NT 6.2) AppleWebKit/536.6...,NaN
420,421,Janelle,Terrington,jterringtonbo@upenn.edu,Female,151 Fallview Trail,26,Pending,NSE,Y,EC,10191,25038,NaN,8178667452,57-615-9921,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8)...,NaN
435,436,Patric,Baily,pbailyc3@canalblog.com,Male,3327 Bayside Center,36,Pending,SE,N,EC,18916,28931,NaN,2639603876,43-670-2172,Mozilla/5.0 (Windows 8) AppleWebKit/534.30 (KH...,NaN
439,440,Thomas,Lodwick,tlodwickc7@google.co.jp,Male,55 La Follette Pass,46,Decline,SE,N,D,9992,22798,NaN,156242001,81-545-0833,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_4_1...,NaN
446,447,Sybyl,Iacovini,siacovinice@sfgate.com,Female,1719 Dovetail Point,40,Decline,NSE,Y,D,16445,22502,NaN,2871962588,80-133-8445,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2)...,NaN
447,448,Woody,Keats,wkeatscf@ovh.net,Male,126 Westerfield Center,43,Decline,NSE,Y,3P,5863,23028,NaN,362942625,99-140-7364,Mozilla/5.0 (X11; Linux i686) AppleWebKit/535....,NaN
459,460,Feliza,Waulker,fwaulkercr@un.org,Female,44965 Mockingbird Way,55,Decline,NSE,Y,MP,24002,25810,NaN,2012666213,30-538-4636,Mozilla/5.0 (Windows NT 6.2) AppleWebKit/537.3...,NaN
462,463,Floyd,Bossingham,fbossinghamcu@globo.com,Male,700 Jackson Trail,43,Decline,NSE,Y,D,14404,21171,NaN,781466822,31-877-6267,Mozilla/5.0 (Windows NT 6.1; rv:22.0) Gecko/20...,NaN
464,465,Ricoriki,Vannuccinii,rvannucciniicw@mayoclinic.com,Male,7925 Starling Road,27,Pending,SE,Y,EC,18527,30071,NaN,8830681768,75-692-1287,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_3)...,NaN
472,473,Quintina,Hughf,qhughfd4@oakley.com,Female,85460 Esch Trail,26,Decline,NSE,Y,3P,17609,27859,NaN,6150949486,38-025-5501,Mozilla/5.0 (Windows; U; Windows NT 6.0; de-DE...,NaN
501,502,Benedick,Delyth,bdelythdx@tmall.com,Male,0873 Carpenter Lane,21,Pending,SE,Y,EC,24222,26597,NaN,6459332681,08-595-5573,Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US...,NaN
503,504,Levy,Gleave,lgleavedz@google.pl,Male,58 Menomonie Avenue,53,Decline,SE,N,MP,8814,21682,NaN,8845315703,58-649-4029,Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US...,NaN
521,522,Sabra,Kobierra,skobierraeh@cmu.edu,Female,50 Huxley Lane,34,Decline,NSE,N,3P,12648,26852,NaN,4008596909,91-735-0008,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,NaN
539,540,Vivyan,Rubinfeld,vrubinfeldez@ebay.co.uk,Female,9714 Chinook Alley,20,Decline,NSE,N,D,11100,30451,NaN,8993215251,06-330-6571,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8)...,NaN
562,563,Gerda,Dupree,gdupreefm@mapy.cz,Female,67515 Golf Course Pass,22,Pending,NSE,Y,EC,12358,27026,NaN,9140162931,82-897-1075,Mozilla/5.0 (iPad; CPU OS 6_0 like Mac OS X) A...,NaN
580,581,Cathie,Baggett,cbaggettg4@house.gov,Female,23652 Esker Place,57,Decline,NSE,Y,D,9679,26814,NaN,9301314010,23-496-9130,Mozilla/5.0 (X11; Linux i686) AppleWebKit/535....,NaN
602,603,Charleen,Toffoloni,ctoffolonigq@latimes.com,Female,20 Forster Street,41,Decline,NSE,N,D,3323,24602,NaN,5690858501,00-654-5794,Mozilla/5.0 (X11; Linux i686) AppleWebKit/534....,NaN
635,636,Lorelei,Veschambre,lveschambrehn@epa.gov,Female,26806 Moose Lane,49,Decline,SE,Y,MP,17362,26922,NaN,3029203050,87-556-3443,Mozilla/5.0 (Windows NT 6.1; rv:14.0) Gecko/20...,NaN
753,754,Miller,Popley,mpopleykx@alexa.com,Male,14106 Duke Avenue,26,Decline,SE,N,D,30019,30210,NaN,5965995342,97-198-9076,Mozilla/5.0 (X11; Linux amd64) AppleWebKit/534...,NaN
757,758,Lin,Oki,lokil1@digg.com,Female,1469 Pennsylvania Parkway,33,Decline,NSE,Y,MP,8339,27112,NaN,5931089977,58-022-3108,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6...,NaN
799,800,Georgie,Jentgens,gjentgensm7@jimdo.com,Female,929 Moose Center,26,Decline,SE,N,MP,20314,30060,NaN,3023758492,74-943-0681,Mozilla/4.0 (Windows NT 6.3; Win64; x64) Apple...,NaN
811,812,Kayle,Ladewig,kladewigmj@va.gov,Female,3850 Pleasure Point,53,Decline,NSE,Y,D,9046,22988,NaN,7007567754,26-940-3152,Mozilla/5.0 (X11; Linux amd64) AppleWebKit/535...,NaN
824,825,Tabbie,Corington,tcoringtonmw@cornell.edu,Male,229 1st Crossing,23,Decline,NSE,Y,D,17697,23984,NaN,5829555808,06-595-7471,Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:22...,NaN
868,869,Doll,Swoffer,dswoffero4@amazon.com,Female,72 Kipling Way,49,Decline,SE,Y,D,6872,22653,NaN,2969346052,19-086-4963,Mozilla/5.0 (Windows NT 5.2; WOW64) AppleWebKi...,NaN
888,889,Alonzo,Oak,aoakoo@simplemachines.org,Male,54 Linden Center,43,Decline,NSE,Y,3P,3039,29392,NaN,1627327061,17-816-0972,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6...,NaN
918,919,Fonz,Fodden,ffoddenpi@symantec.com,Male,36 Comanche Drive,28,Decline,NSE,Y,3P,9315,28786,NaN,8822208498,51-971-5682,Mozilla/5.0 (X11; Linux amd64) AppleWebKit/535...,NaN

# total application

In [25]:
TA=df["Application id"].nunique()

# approved application

In [26]:
AP=(df["tdecision"]=="Approve").sum()

# booked application

In [27]:
BA=(df["Booking"]=="Y").sum()

# approval rate

In [29]:
AR=AP/TA

# booking rate

In [31]:
BR=BA/AP

# new booking amount

In [37]:
NBA=df.Booking_Amt.sum()

In [38]:
metrics=pd.DataFrame({"total application":TA,"approved application":AP,"booked application":BA,"approval rate":AR,"booking rate":BR,"new booking amount":NBA},index=[0])

In [39]:
metrics

,total application,approved application,booked application,approval rate,booking rate,new booking amount
0,1000,699,581,0.699,0.831187,253804130.1

In [44]:
metrics.to_excel("metrics.xlsx")